service: sls-stepfunctions-hello

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, 'us-west-1'}
  stage: ${opt:stage, 'dev'}
  # lambdaHashingVersion: 20201221

plugins:
  - serverless-step-functions
  - serverless-esbuild

functions:
  helloWorld:
    name: helloWorld
    handler: src/handler.message

stepFunctions:
  stateMachines:
    helloWorld:
      name: ${self:service}-${self:provider.stage}-statemachine
      definition:
        Comment: "Hello World AWS Step Function with serverless-step-functions plugin for Serverless Framework"
        StartAt: "Hello"
        States:
          Hello:
            Type: Task
            Resource:
              Fn::GetAtt:
                - helloWorld
                - Arn
            OutputPath: "$.Payload"
            Parameters:
              Payload.$: "$"
            Next: Succeed
          Succeed:
            Type: Succeed
# resources:
#   # Outputs:
#   #   helloWorld:
#   #     Export:
#   #       Name: "Hello World State Machine"
#   #     Value:
#   #       Ref: helloWorld
