service: sls-stepfunctions-hello

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-1
  lambdaHashingVersion: 20201221

#  stage: dev
#  region: us-west-1

stepFunctions:
  stateMachines:
    helloWorldFlow:
      definition:
      comment: "Hello World AWS Step Function with serverless-step-functions plugin for Serverless Framework"
        startAt: "Wait for Timer"
        States:
          Wait for Timer:
            Type: Wait
            SecondsPath: "$.timer_seconds"
            Next: Success
          Success:
            Type: Succeed
